# =========================
# Server
# =========================
server.port=${SERVER_PORT:8080}

# =========================
# Datasource
# =========================
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# =========================
# JPA
# =========================
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# =========================
# SECURITY
# =========================
security.min-password-length=6

# =========================
# FILE UPLOAD
# =========================
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

# =========================
# LIQUIBASE
# =========================
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml

# =========================
# LOGGING
# =========================
logging.level.root=INFO
logging.level.ru.skypro=INFO
logging.level.org.springframework.boot.autoconfigure.liquibase=INFO
logging.level.liquibase=INFO

# =========================
# ALFRESCO
# =========================
alfresco.url=${ALFRESCO_URL}
alfresco.username=${ALFRESCO_USERNAME}
alfresco.password=${ALFRESCO_PASSWORD}
alfresco.folder-id=${ALFRESCO_FOLDER_ID}

# =========================
# SWAGGER
# =========================
springdoc.api-docs.enabled=false
springdoc.swagger-ui.enabled=false