# Настройки Spring Boot
spring.messages.basename=messages
spring.messages.encoding=UTF-8

# =========================
# Server
# =========================
server.port=8080

# =========================
# Datasource
# =========================
spring.datasource.url=jdbc:postgresql://localhost:5432/java_graduate_work
spring.datasource.username=java_user
spring.datasource.password=java

# =========================
# JPA
# =========================
# Hibernate ddl auto (create, create-drop, validate, update, none)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect