# Настройки Spring Boot
spring.messages.basename=messages
spring.messages.encoding=UTF-8
# =========================
# Server
# =========================
server.port=8080
# =========================
# Datasource
# =========================
spring.datasource.url=jdbc:postgresql://localhost:5432/java_graduate_work
spring.datasource.username=java_user
spring.datasource.password=java
# =========================
# JPA
# =========================
# Hibernate ddl auto (create, create-drop, validate, update, none)
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# =========================
# SECURITY
# =========================
security.min-password-length=6

# ============================================
# ЗАГРУЗКА ФАЙЛОВ
# Максимальный размер
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB
# Путь хранения файлов аватарок
app.storage.file-avatar-path=${user.home}/java_graduate_work/avatar

# =========================
# LIQUIBASE
# =========================
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml

# =========================
# ALFRESCO
# =========================
alfresco.url=http://localhost:9090/alfresco
alfresco.username=alfresco
alfresco.password=alfresco

# nodeId заранее созданной папки avatars
alfresco.folder-id=xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
