# URL базы данных
url=jdbc:postgresql://localhost:5432/java_graduate_work
# Имя пользователя
username=postgres
# Пароль
password=
# Драйвер
driver=org.postgresql.Driver
# Файл с миграциями
changeLogFile=src/main/resources/db/changelog/db.changelog-master.yaml